### ISSUE TITLE
Version/channel tracking of apps from DHIS2 instances

### ISSUE THREAD

**Issue by erikarenhill** [dhis2/app-hub#153]
Since the implementation of release channels we also need to consider a few new things seen from a DHIS2 instance perspective.

An instance is following stable apps by default, but should be allowed to switch channel for a specific app. I.e. running stable for all apps except app X that we want to use from the Development channel.

The questions/thoughts: 
* How do we track updates regarding the app X from the Development channel?
* Should we allow the app X to be installed from both Stable and Development simultaneously side by side?
* What should happen when an app change channel in the backend, for example version 1.2 moves from Development to Release, and should we allow it at all? 
* How do we guarantee deterministic builds? I.e. version 1.2.3 of app X should always be the same no matter which channel it comes from (if published in N+1 channels at the same time)

Me and @varl discussed solutions involving the App management app to store this kind of meta data in the dataStore which app/version/package combination that is tracked from which channel. That way we can query the backend if there are new versions for that app from the specific channel, given that the app does not change name.

**Comment by varl** [comment]
> What should happen when an app change channel in the backend, for example version 1.2 moves from Development to Release, and should we allow it at all?

I had a discussion with @Philip-Larsen-Donnelly last week where we decided to drop the "promoted versions" flow and align closer to what we have today.

> How do we track updates regarding the app X from the Development channel?

Same as with the other channels. App management shows that there is a new version and you have the option to update to it.

> How do we guarantee deterministic builds? I.e. version 1.2.3 of app X should always be the same no matter which channel it comes from (if published in N+1 channels at the same time)

Deterministic builds is guaranteed on an artifact level, but the same artifact can be deployed to multiple channels (though probably shouldn't).

> Should we allow the app X to be installed from both Stable and Development simultaneously side by side?

Yes, we need to figure out how to differentiate between them though. And if we can limit access to e.g. the development version to a subset of users (administrators, for example).

**Comment by erikarenhill** [comment]
Thoughts/questions:

1. Can we start off the new app hub with an empty database? E.g. everyone that wants their app to stay have to upload it again.
2. We should enable DHIS2 core to present the apps through a versioned URL, both without the /api and with a channel/app version in it

**Comment by Philip-Larsen-Donnelly** [comment]
@erikarenhill what is the rational behind point 1? and would it impact 2.34?

**Comment by erikarenhill** [comment]
> @erikarenhill what is the rational behind point 1? and would it impact 2.34?

Me and @varl  discussed this earlier due to there is lots of test/junk- apps in the current database. Also I'm digging around and update the commend above meanwhile so its kind of work in progress/note

**Comment by Philip-Larsen-Donnelly** [comment]
OK. My main comment would be that there may be people somewhere who rely on those test/junk apps for some reason and we should avoid the case that things simply disappear because we have updated the platform. At the very least we should give ample warning to the community, and ideally maintain access to as much as possible, even if that means "unclaimed" apps are somehow demoted to relevant channels.

**Comment by erikarenhill** [comment]
We will somehow make sure the current published apps is available when 2.34 goes live, only unapproved/rejected apps called stuff like "fdasfdsa" or apparant "Hello world" -apps might be lost.
